name: Manual Workflow

on:
  workflow_dispatch: # 手動でトリガーする

jobs:
  manual_job:
    name: Execute Manually
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 # リポジトリをチェックアウト

      - name: Run a shell command
        run: |
          echo "This workflow was triggered manually."
          # ここに実行したいコマンドを追加
