name: Manual Workflow

on:
  workflow_dispatch: # 手動でトリガーする

jobs:
  manual_job:
    name: Execute Manually
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 # リポジトリをチェックアウト

      - name: Run hello.py script
        run: python hello.py
