name: Weekly Workflow

on:
  schedule:
    - cron: "30 0 * * 1" # 毎週月曜日の0:30に実行する

jobs:
  weekly_job:
    name: Execute Weekly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 # リポジトリをチェックアウト

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client

      - name: Run main.py script
        env:
            API_KEY: ${{ secrets.API_KEY }} # secretsに登録した環境変数
            WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }} # DiscordのWebhook URLを環境変数から取得
        run: python main.py

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add latest_video_id.txt
          git commit -m "Auto-publish changes from GitHub Actions"
          git push origin main
